### ISSUE TITLE
Group letters in the checksum worksheet.

### ISSUE THREAD

**Issue by roconnor-blockstream** [roconnor-blockstream/SSS32#13]
To help users make sure they do not get lost, try to delimit groups of 4 letters, and super groups of 16 letters.  This aligns with the grouping of characters on a cryptosteel.

**Comment by apoelstra** [comment]
Relatedly, it would be nice to have a 3-letter HRP so that you can put e.g. `sss1` as the first group in the cryptosteel.

**Comment by roconnor-blockstream** [comment]
I get it.  But I still somewhat prefer the tradeoff of `ms1` and then getting an extra index character.

**Comment by apoelstra** [comment]
Ah, yep, I can definitely get behind that.

I had thought the plan was to have `ms321` which would have one *too many* characters, and that would be a problem.

**Comment by roconnor-blockstream** [comment]
Also I think numbering every input square with its ordinal position.

**Comment by apoelstra** [comment]
Can this be closed now?

**Comment by roconnor-blockstream** [comment]
Fixed in faed773f70b9500c78f166a1442031e05381a716.
