### ISSUE TITLE
Turn Recover Share volvelle into a table.

### ISSUE THREAD

**Issue by roconnor-blockstream** [roconnor-blockstream/SSS32#18]
There are very few lookups needed in the Recover Share processes.  And, because this volvelle isn't symetric, a table lookup can more clearly label the purpose of the axes.

**Comment by apoelstra** [comment]
I think we should provide both forms

**Comment by roconnor-blockstream** [comment]
Fair point.  Probably everything should have a table and a volvelle format.

**Comment by roconnor-blockstream** [comment]
Fixed in 38123e3dd2ad5ac9b7be7436625a9793efa11d55.
