### ISSUE TITLE
Why not build this for one time pads?

### ISSUE THREAD

**Issue by mchapiro1** [roconnor-blockstream/SSS32#36]
See this for reference:

https://github.com/brndnmtthws/seed-otp

I think it would be faster and more intuitive. Not sure the advantage of this approach.

**Comment by apoelstra** [comment]
You can use this for one-time-pads, by doing 2-of-2 secret sharing where you start with your original secret, generate a random share (the "encryption key") and derive another share (the "ciphertext"). It will be more complex and time-consuming than a dedicated OTP scheme, but on the other hand your ciphertext will be checksummed.

But this scheme's goal is not to do OTP, but to do Shamir Secret Sharing, so the two schemes aren't really substitutes for each other.

**Comment by roconnor-blockstream** [comment]
Also an OTP doesn't really come with a checksum to check your work. If you make an error with an OTP then it is unrecoverable.  I mean, you can maybe bolt on a checksum, but if you do then you will reproduce 90% of using our scheme in a 2-of-2 setting.

**Comment by roconnor-blockstream** [comment]
P.S. I've opened up the [discussions forum](https://github.com/roconnor-blockstream/SSS32/discussions) which is a great place for questions like this.  If you are not satisfied with the answers here, feel free to resubmit your question to the discussion section.
