### ISSUE TITLE
Redo layout of top disc

### ISSUE THREAD

**Issue by roconnor-blockstream** [roconnor-blockstream/SSS32#5]
It is somewhat hard to find the letters on the top disc with the current layout.  Assuming the layout of the holes remains unchanged, there is a fairly clear set of 5 spiral, 2 spirals with 7 holes, and 3 spirals with 6 holes.  Placing letters in alphabetical order along these spirals may make finding letters easier.

**Comment by apoelstra** [comment]
See https://github.com/apoelstra/SSS32/commit/360a05bb0f7ee402930c2f6bf2c7823d5cecee1f for my suggestion
